version: '3.2'
volumes:
  kong-db:
    driver: local
services:
  oms:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - oms
      - environment_kong-net
      - environment_kafka
    depends_on:
      - postgresql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/oms
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      BOOTSTRAP_SERVERS: kafka:9092
      ISSUER_URI: http://iam:8080
  postgresql:
    image: postgres
    restart: always
    networks:
      - oms
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oms
    ports:
      - '5433:5432'
networks:
  environment_kong-net:
    driver: overlay
    external: true
  oms:
    driver: bridge
  environment_kafka:
    driver: overlay
    external: true