server:
  port: 8082
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/oms
    username: user
    password: password